general:
  name: qm9
  # wandb: disabled
  # sample_every_val: 4
  # samples_to_generate: 512
  # samples_to_save: 20
  # chains_to_save: 1
  log_every_steps: 50
  number_chain_steps: 50
  # final_model_samples_to_generate: 10000
  # final_model_samples_to_save: 30
  # final_model_chains_to_save: 20
model:
  type: discrete
  transition: marginal
  model: graph_tf
  diffusion_steps: 500
  diffusion_noise_schedule: cosine
  n_layers: 5
  extra_features: null # 'all' 
  hidden_mlp_dims:
    X: 256
    E: 128
    'y': 128
  hidden_dims:
    dx: 256
    de: 64
    dy: 64
    n_head: 8
    dim_ffX: 256
    dim_ffE: 128
    dim_ffy: 128
  lambda_train:
  - 5
  - 0
  input_dims: {'X': 4, 'E': 5, 'y': 1} # {'X': 12, 'E': 5, 'y': 13}
  output_dims: {'X': 4, 'E': 5, 'y': 0} # {'X': 4, 'E': 5, 'y': 0}
  torch_compile: false
train:
  # n_epochs: 100
  batch_size: 512
  lr: 0.0002
  save_model: true
  num_workers: 16
  weight_decay: 1.0e-12
  # optimizer: adamw
dataset:
  name: qm9
  datadir: data/qm9/qm9_pyg/
  remove_h: true
  pin_memory: false
