# @package _global_
general:
    # General settings
    name: 'regressor'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

    wandb: 'online'             # online | offline | disabled
    gpus: 1                     # Multi-gpu is not implemented on this branch

    guidance_target: 'both'       # null is the default when not using guidance. Otherwise, use 'homo', 'mu' or 'both'

    resume: null            # If resume, path to ckpt file from outputs directory in main directory
    test_only: null         # Use absolute path
    remove_h: True
    check_val_every_n_epochs: 5
    sample_every_val: 4
    val_check_interval: null
    samples_to_generate: 512       # We advise to set it to 2 x batch_size maximum
    samples_to_save: 20
    chains_to_save: 1
    log_every_steps: 50
    number_chain_steps: 50        # Number of frames in each gif

    final_model_samples_to_generate: 10000
    final_model_samples_to_save: 30
    final_model_chains_to_save: 20

    evaluate_all_checkpoints: False

train:
    n_epochs: 1200
    batch_size: 512
    save_model: True
    num_workers: 12
    progress_bar: False
    lr: 0.0002
    clip_grad: null          # float, null to disable
    ema_decay: 0           # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
    weight_decay: 1e-12
    optimizer: adamw # adamw,nadamw,nadam => nadamw for large batches, see http://arxiv.org/abs/2102.06356 for the use of nesterov momentum with large batches
    amsgrad: true
    overfit: False
    seed: 0
model:
    n_layers: 5
    lambda_train: [2, 0]
    extra_features: null
    type: 'discrete'
    transition: 'marginal'                          # uniform or marginal
    model: 'graph_tf'
    diffusion_steps: 500
    diffusion_noise_schedule: 'cosine'              # 'cosine', 'polynomial_2'

    # Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
    # At the moment (03/08), y contains quite little information
    hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}

    # The dimensions should satisfy dx % n_head == 0
    hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}


dataset:
    name: qm9
    datadir: data/qm9/qm9_pyg/
    remove_h: True
    random_subset: null
    pin_memory: false
